project_id = "jdkispdudszhskqfylkd"

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.discord-webhook]
verify_jwt = false
